spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: customers
  profiles:
    active: production

# ACTUATOR INFO
info:
  app:
    name: "Customers"
    version: "0.0.1"
    profile: ${spring.profiles.active}
  serverInfo:
    port: ${server.port}

management:
  endpoints:
    web:
      exposure:
        include: '*'

application:
  allow-get-customers: ${accounts.allow-get-customers}